engines:
  cppcheck:
    enabled: true
    config:
      check: all
      project: compile_commands.json
      language: c++
      stds:
        - c++17
      platform: unix64
      max_configs: 42
      inconclusive: false
