distr: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libx11-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libx11-dev
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- dwm-statusbar -j
  - cmake --build . -- ut -j
