sudo: required
language: cpp
distr: xenial

stages:
  - linting
  - test

matrix:
  include:
    - os: linux
      addons:
        apt:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libx11-dev
            - libboost-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libx11-dev
            - libboost-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libx11-dev
            - libboost-all-dev
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- dwm-statusbar -j
  - cmake --build . -- ut -j

jobs:
  - stage: linting
    addons:
      apt:
        - llvm-toolchain-trusty-6.0
      packages:
        - clang-format-6.0
    script:
      - clang-format -style=file
